### ISSUE TITLE
Moving posts when having buckets open causes a memory issue

### ISSUE THREAD

**Issue by l3n0ire** [encorelab/ck-board#151]
# Steps to reproduce
- Checkout develop branch
- Open a board, then create and open a bucket
- Add a post from the board to the bucket
- Then move the post

# Result
- Post moves very slowly and ck board starts lagging
- In worst case, chrome runs out of memory

# Potential cause
- When a post is moved, all other clients are alerted and update the position of that post on their boards
- Maybe Buckets are causing extra call or infinite loop somewhere?

**Comment by l3n0ire** [comment]
@Ammar-T  any idea what could be causing this?  This doesn't affect posts that are added only the bucket.

**Comment by Ammar-T** [comment]
@l3n0ire Yeah I noticed this yesterday as well, I added a fix for it in this branch https://github.com/encorelab/ck-board/compare/develop...issue-buckets-list-redesign. I currently need to make a couple more changes then I'll merge this into develop. Just cleaning some stuff up before the next merge to master.

Also, could you try to avoid causing that issue as well since it eats up a lot of the firebase reads/write calls. I didn't realize this yesterday and hit our daily quota lol.
