### ISSUE TITLE
"Clear Board" button 

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#159]
Allow users to clear the canvas which means removing all posts currently on the canvas. 

However, this should keep those posts visible in the list view or bucket view (if it was assigned to buckets), so it's not completely gone. 

Add a permission for who can see this button (i.e. only for teachers, or both)

**Comment by JoelWiebe** [comment]
@Ammar-T Was this something that Jim had suggested? I think the use case was that posts could be sent to a bucket, then the board could be cleared for students to do other work. 

Therefore, could we edit this description slightly so that we are just removing the location information from each post so that the posts exist in the list view or any buckets that they are affiliated with but are only removed from the canvas to free the canvas for other work?

**Comment by Ammar-T** [comment]
@JoelWiebe Honestly cant remember why/who suggested this (it might've been me). Feels like it was created ages ago when it was only 4 months haha.

I'll update the description to your suggestion since that makes a lot of sense! "Clearing the board" should strictly do what it means.

**Comment by JoelWiebe** [comment]
Hahahaha, yes @Ammar-T, these software projects grow up so fast :)

(Let's put this button in the board configurations for now so that only teachers can press it!)

**Comment by LunarFang416** [comment]
@JoelWiebe how would we want to log clearing posts from the post in trace? Should I create a separate field or do a postRemove followed by a createPost socket event which will create a log in that order as well?

**Comment by JoelWiebe** [comment]
@LunarFang416 Good question. Hmm, I'm debating between either logging a single "clear board" event or logging the removal of each post. I'm leaning toward us creating an eventType Clear_Board is triggered a single time that identifies the user who cleared the board, the project, the board, and whatever else seems pertinent.

**Comment by LunarFang416** [comment]
@JoelWiebe I agree, a separate ClearBoard event will be better since it would be confusing to differentiate between an actual post removal and removing several posts at once by doing clear board.
