### ISSUE TITLE
Delete boards

### ISSUE THREAD

**Issue by Ammar-T** [encorelab/ck-board#252]
Delete boards within a project which also removes any data associated with it (i.e. posts, likes, comments, etc.). 

The delete button can be somewhere inside the settings modal.

**Comment by JoelWiebe** [comment]
Yeah, it's a tricky design question. I'm reflecting back on one of my previous professors' voice, he had a design principle that a user should always be able to undo their action to prevent possible negative consequences for them. He tended to avoid the "are you sure" boxes because those were not always read and couldn't be undone. I realize it's a lot more work, but would it make sense to have a "move to trash" then "permanently delete from trash" options? Is running out of space a real problem for us if we have lots of extra boards or what is our strongest argument for permanently delete at this point? 

I'd be fine if either we (1) implement flag or trash can now, then later implement a permanently delete from trash feature or (2) delete permanently with a confirmation dialogue -- as in most cases that should be enough. Please go with whichever option you think is best given all current constraints!

**Comment by JoelWiebe** [comment]
Let's do permanent delete with confirmation dialogue for now, then revisit in the future if needed.
