### ISSUE TITLE
Allow Board Creation without Tasks

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#267]
From the project page, allow users to create boards that specify only a name, but do not require a task.

**Comment by LunarFang416** [comment]
@JoelWiebe When i was working on issue #233 to require a task title, i inferred from the screenshot in the issue that because it said "No Task Created", it meant that tasks weren't mandatory when creating a board. So I made some changes when creating a board as well so you don't need to create a task to create a board (it still requires a task title when there is a task message though). :)

You can look at the commits for my PR #266, and please let me know if that addresses this issue as well.

**Comment by LunarFang416** [comment]
Yep.
