### ISSUE TITLE
Error uploading images to canvas bg

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#89]
When uploading images I get an error in the browser console
![image](https://user-images.githubusercontent.com/6416247/137339310-35477b2a-503b-494a-ae08-e964340556ed.png)

To reproduce:
- I uploaded an svg (which usually works)
- then a png and a jpg (which both throw the error)

The image sometimes flickers on the screen before disappearing

**Comment by JoelWiebe** [comment]
@Ammar-T I've now been able to upload pngs but when I replace the png with a jpg I get the above error. For now should we just drop support for JPG until we can sort this out (i.e., only allow users to select and upload pngs for instance)?

**Comment by Ammar-T** [comment]
@JoelWiebe I'll look further into this, although I don't think the issue is caused by images being `.jpg`. I'll let you know!

**Comment by Ammar-T** [comment]
@JoelWiebe So the problem was that with `.jpg` and `.jpeg` images, when they're encoded to string format, they're simply too large to store in Firebase. So for now, I've restricted uploads to just `.svg` and `.png`. Note that this error may still occur for very large `.png` or `.svg`. 

In the future, we should look to an alternative image storing system (maybe AWS S3?) which will allow us to store larger images. But for now, the updated implementation should be fine.

**Comment by JoelWiebe** [comment]
@Ammar-T Thanks for investigating this! I really appreciate the explanation. Would video compression be a fair place to start -- we had used some kind of image compression for SCORE.

@hirokiterashima was this what we used in SCORE for image compression: https://www.npmjs.com/package/ngx-image-compress

**Comment by hirokiterashima** [comment]
@JoelWiebe- you're probably thinking about the [ng-file-upload library](https://github.com/danialfarid/ng-file-upload) that we use to allow students to upload assets? The library resizes large images before we upload them to the server. Also, this library is in AngularJS, not Angular. Here's the [relevant code](https://github.com/encorelab/SCORE-Client/blob/012631cbee7a58dffb8edfb4a239cfee5eab0087/src/assets/wise5/themes/default/studentAsset/studentAsset.html#L71).
