### ISSUE TITLE
Background images skewed

### ISSUE THREAD

**Issue by JoelWiebe** [encorelab/ck-board#95]
Successfully uploaded background images are displayed with incorrect aspect ratio causing the image to appear skewed

**Comment by JoelWiebe** [comment]
@Ammar-T @l3n0ire Any chance we could look into this? I also notice that images present at different sizes on the board. Maybe we can have a fixed default size of a background image on the canvas.

Jim is hoping to do a test run in his class in a week or two and wanted to try out backgrounds and tagging. If we could do a quick pass to be able to upload PNGs and get them presenting at a standard size without the image looking stretched that would be really helpful!

**Comment by Ammar-T** [comment]
> @Ammar-T @l3n0ire Any chance we could look into this? I also notice that images present at different sizes on the board. Maybe we can have a fixed default size of a background image on the canvas.
> 
> Jim is hoping to do a test run in his class in a week or two and wanted to try out backgrounds and tagging. If we could do a quick pass to be able to upload PNGs and get them presenting at a standard size without the image looking stretched that would be really helpful!

**Comment by Ammar-T** [comment]
@JoelWiebe Yeah I can take this on now. 

FYI: Accidentally closed the issue, you can ignore that :)

**Comment by Ammar-T** [comment]
@JoelWiebe At the moment, the uploaded background image fits to the user's canvas view. So, if they zoom in a little bit, the image would be smaller. If they zoom out, the image will be larger since the area of the canvas is larger. I did it this way so users can have some freedom with picking the size of the image.

Also, I'm not sure why images may look stretched or with an incorrect aspect ratio since my implementation should handle that. I've tried uploading images with different zoom depths to test it out and everything looks good to me. Do you have an example for me to reproduce that issue?

**Comment by JoelWiebe** [comment]
@Ammar-T Oh that is ingenious; "zoom canvas to desired background image size"! Could we add this message to the config page so teachers are aware of this? I really like that implementation, I just never caught on, lol. 

For the aspect ratio, it seems that all images I upload are stretched somehow e.g., 

Screenshot
![image](https://user-images.githubusercontent.com/6416247/151237593-656f3dc9-1dc6-4709-afce-0f6c0bf49727.png)

Original image
![3 - Summary Document](https://user-images.githubusercontent.com/6416247/151237660-c90c8f87-6d8d-48fc-aa89-d5e47933adfa.png)

**Comment by JoelWiebe** [comment]
@Ammar-T Is this something that @StevenWuzz could look into?

**Comment by Ammar-T** [comment]
@JoelWiebe Yeah, @StevenWuzz can take this on.
